# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [3]:
arrA = np.array([[11, 12, 13], 
                 [14, 15, 16]])
print("arrA:\n", arrA)

arrA:
 [[11 12 13]
 [14 15 16]]


In [4]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [5]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


In [6]:
for x in arrA:
    for y in x:
        loop_result = y * 2

print("loop_result:", loop_result)

loop_result: 32


In [7]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print("joined_array_1:\n", joined_array_1)

joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print("joined_array_2:\n", joined_array_2)

stacked_array_1 = np.stack((joined_array_1, joined_array_1), axis=0)
print("stacked_array_1:\n", stacked_array_1)

joined_array_1:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
joined_array_2:
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
stacked_array_1:
 [[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [8]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print("another_joined_array:\n", another_joined_array)

another_joined_array:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [9]:
stacked_h = np.hstack((arrA, arrA)) # Stacks arrays horizontally (column-wise)
stacked_v = np.vstack((arrA, arrA)) # Stacks arrays vertically (row-wise)
stacked_d = np.dstack((arrA, arrA)) # Stacks arrays depth-wise (3D)

In [10]:
print("hstack:\n", stacked_h)
print("vstack:\n", stacked_v)
print("dstack:\n", stacked_d)

hstack:
 [[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
vstack:
 [[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
dstack:
 [[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


In [12]:
splitsky = np.array_split(joined_array_1, 2)
print("splitsky:\n", splitsky)
# This results in a list of 2 separate arrays. Each array has 2 dimensions (2 rows and 3 columns)[cite: 49, 50].

splitsky:
 [array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [13]:
spliterino = np.array_split(joined_array_1, 3)
print("spliterino:\n", spliterino)
# This results in a list of 3 separate arrays. Since 4 rows cannot be divided evenly by 3, 
# the first array gets 2 rows, and the remaining two arrays get 1 row each. 
# All remain 2-dimensional[cite: 51, 52].

spliterino:
 [array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [14]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print("result_1:\n", result_1)

result_1:
 [['odd' '12' 'odd']
 ['14' 'odd' '16']]


In [15]:
arrB = np.array([[7, 6], [13, 5], [7, 3]])
arrB_sorted = np.sort(arrB)
print("arrB_sorted:\n", arrB_sorted)

arrB_sorted:
 [[ 6  7]
 [ 5 13]
 [ 3  7]]


In [16]:
print("Original arrB:\n", arrB)
z = arrB < 7
arrC = arrB[z]
print("arrC:\n", arrC)

Original arrB:
 [[ 7  6]
 [13  5]
 [ 7  3]]
arrC:
 [6 5 3]


In [17]:
y = arrB >= 7
arrD = arrB[y]
print("arrD:\n", arrD)

arrD:
 [ 7 13  7]
