# Markdown: # Exercise 1.B NumPy Random

In [2]:
import numpy as np

In [3]:
r_1 = np.random.randint(1, 20, size=2)
print("r_1:", r_1)

r_1: [13  5]


In [4]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print("r_2:", r_2)

r_2: [[3 1]]


In [5]:
r_3 = np.random.rand(2, 1)
print("r_3:\n", r_3)

r_3:
 [[0.12360455]
 [0.96901784]]


In [7]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print("r_4:\n", r_4)

r_4:
 [[59 72 50 85 20]
 [86 68 35 21 86]
 [36 85 65 58 89]
 [38 60 81 30 45]]


In [8]:
r_5 = np.random.rand(4, 5)
print("r_5:\n", r_5)

r_5:
 [[0.82744251 0.86018785 0.31961575 0.23798443 0.6381361 ]
 [0.18161611 0.80576252 0.67527917 0.1349078  0.38242447]
 [0.43250372 0.47805827 0.74798637 0.64610487 0.10849134]
 [0.33851929 0.57541    0.53072619 0.56379767 0.58504916]]


In [9]:
students = np.array(['Ali', 'Ayşe', 'Fatma', 'Ahmet', 'Mehmet', 'Can', 'Cem', 'Deniz', 'Ege', 'Eda', 'Gül', 'Naz'])

In [10]:
call_on = np.random.choice(students)
print("call_on:", call_on)

call_on: Mehmet


In [11]:
breakout_groups = np.random.choice(students, size=(3, 4))
print("breakout_groups:\n", breakout_groups)

breakout_groups:
 [['Fatma' 'Gül' 'Ali' 'Ayşe']
 ['Fatma' 'Eda' 'Ahmet' 'Ayşe']
 ['Cem' 'Fatma' 'Ege' 'Mehmet']]


In [12]:
p_values = [0.30, 0.0, 0.10, 0.10, 0.05, 0.05, 0.10, 0.05, 0.05, 0.05, 0.05, 0.10]
call_on_weighted = np.random.choice(students, size=5, p=p_values)
print("call_on_weighted:", call_on_weighted)

call_on_weighted: ['Mehmet' 'Ali' 'Naz' 'Mehmet' 'Fatma']


In [13]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print("bell_curve:\n", bell_curve)

bell_curve:
 [[ 6.75292938  3.63783463 -0.93357238 17.35598666 -3.67420783]
 [ 3.28414957  5.1984875  13.34231512  9.32463321 18.52107777]
 [16.00105442  8.99089603  3.41863429  1.39929091 20.46013717]
 [ 3.14980938 16.20490236  7.59281771 14.29601037 16.30043403]]
