# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

In [2]:
r_1 = np.random.randint(1, 20, size=2)

In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))

In [4]:
r_3 = np.random.rand(2, 1)

In [5]:
r_4 = np.random.randint(20, 100, size=(4, 5))

In [6]:
r_5 = np.random.rand(4, 5)

## Permutations

In [ ]:
print("r_4 (original):\n", r_4) 
np.random.shuffle(r_4) 
print("r_4 (shuffled):\n", r_4) 

r_4 (original):
 [[84 56 58 20 61]
 [52 93 31 44 23]
 [92 74 74 76 89]
 [65 86 91 57 25]]
r_4 (shuffled):
 [[84 56 58 20 61]
 [65 86 91 57 25]
 [52 93 31 44 23]
 [92 74 74 76 89]]


In [ ]:
new_shuffle = np.random.permutation(r_4) 
print("new_shuffle:\n", new_shuffle) 
print("r_4 again:\n", r_4) 

new_shuffle:
 [[52 93 31 44 23]
 [92 74 74 76 89]
 [84 56 58 20 61]
 [65 86 91 57 25]]
r_4 again:
 [[84 56 58 20 61]
 [65 86 91 57 25]
 [52 93 31 44 23]
 [92 74 74 76 89]]


## Mathematical Operations

In [12]:
print("r_1:", r_1, r_1.shape)
print("r_2:", r_2, r_2.shape)
print("r_1 + r_2:", np.add(r_1, r_2), np.add(r_1, r_2).shape)

r_1: [4 9] (2,)
r_2: [[ 2 19]] (1, 2)
r_1 + r_2: [[ 6 28]] (1, 2)


In [13]:
print("r_1:", r_1, r_1.shape) 
print("r_3:", r_3, r_3.shape) 
print("r_1 + r_3:", np.add(r_1, r_3), np.add(r_1, r_3).shape)

r_1: [4 9] (2,)
r_3: [[0.75211184]
 [0.90597307]] (2, 1)
r_1 + r_3: [[4.75211184 9.75211184]
 [4.90597307 9.90597307]] (2, 2)


In [14]:
print("r_2:", r_2, r_2.shape) 
print("r_4:", r_4, r_4.shape)

r_2: [[ 2 19]] (1, 2)
r_4: [[84 56 58 20 61]
 [65 86 91 57 25]
 [52 93 31 44 23]
 [92 74 74 76 89]] (4, 5)


In [15]:
print("r_4 + [1]:\n", np.add(np.array([1]), r_4))
print("r_4 + [[1]]:\n", np.add(np.array([[1]]), r_4))
print("r_4 + [1,1,1,1,1]:\n", np.add(np.array([1,1,1,1,1]), r_4))

r_4 + [1]:
 [[85 57 59 21 62]
 [66 87 92 58 26]
 [53 94 32 45 24]
 [93 75 75 77 90]]
r_4 + [[1]]:
 [[85 57 59 21 62]
 [66 87 92 58 26]
 [53 94 32 45 24]
 [93 75 75 77 90]]
r_4 + [1,1,1,1,1]:
 [[85 57 59 21 62]
 [66 87 92 58 26]
 [53 94 32 45 24]
 [93 75 75 77 90]]


In [16]:
#ValueError: operands could not be broadcast together with shapes (2,1) (4,5)

In [17]:
print("r_3:\n", r_3) 
print("trunc:\n", np.trunc(r_3))
print("fix:\n", np.fix(r_3))
print("ceil:\n", np.ceil(r_3))
print("round:\n", np.round(r_3, 2))

r_3:
 [[0.75211184]
 [0.90597307]]
trunc:
 [[0.]
 [0.]]
fix:
 [[0.]
 [0.]]
ceil:
 [[1.]
 [1.]]
round:
 [[0.75]
 [0.91]]


## Cumulative Operations

In [18]:
print("r_4:\n", r_4) 
print("Sum all:", np.sum(r_4)) 
print("Sum axis 0:", np.sum(r_4, axis=0))
print("Sum axis 1:", np.sum(r_4, axis=1)) 
print("Cumsum all:\n", np.cumsum(r_4))
print("Cumsum axis 0:\n", np.cumsum(r_4, axis=0))

r_4:
 [[84 56 58 20 61]
 [65 86 91 57 25]
 [52 93 31 44 23]
 [92 74 74 76 89]]
Sum all: 1251
Sum axis 0: [293 309 254 197 198]
Sum axis 1: [279 324 243 405]
Cumsum all:
 [  84  140  198  218  279  344  430  521  578  603  655  748  779  823
  846  938 1012 1086 1162 1251]
Cumsum axis 0:
 [[ 84  56  58  20  61]
 [149 142 149  77  86]
 [201 235 180 121 109]
 [293 309 254 197 198]]


## Grocery Problem

In [19]:
bag1 = np.array([2, 3, 4, 0]) 
bag2 = np.array([4, 0, 1, 2]) 
print("bag1:", bag1, "bag2:", bag2)

bag1: [2 3 4 0] bag2: [4 0 1 2]


In [20]:
print(f"The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.") 
totals = bag1 + bag2
print(f"There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.")

The first bag contains 9 items, and the second bag contains 7 items.
There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [22]:
ali = np.array([5, 4, 6, 4, 2]) 
ben = np.array([0, 5, 5, 3, 4]) 
carla = np.array([3, 6, 0, 3, 4])

In [23]:
all_knocks = np.vstack((ali, ben, carla))
print("all_knocks:\n", all_knocks)

all_knocks:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [24]:
print("Ali total:", np.sum(ali)) 
print("Ben total:", np.sum(ben)) 
print("Carla total:", np.sum(carla)) 
print("Group total:", np.sum(all_knocks))

Ali total: 21
Ben total: 17
Carla total: 16
Group total: 54


In [25]:
daily_totals = np.sum(all_knocks, axis=0)
rolling_votes = np.cumsum(daily_totals) * 0.5
print("Rolling total estimated votes:", rolling_votes)

Rolling total estimated votes: [ 4.  11.5 17.  22.  27. ]
